"""
Django settings for yume project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from pathlib import Path
import os
import sys

# Загружаем переменные окружения из .env (если есть)
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()  # загружаем .env

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-temp-key-for-demo-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # для разработки разрешаем все хосты

# Application definition
INSTALLED_APPS = [
    'humanize',
    'anime',
    'users',
    'captcha',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'anime.templatetags.webp',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'anime.middleware.SearchEngineMiddleware',
    'yume.middleware.BlockSitemapMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'yume.middleware.SEOHeadersMiddleware',
]

ROOT_URLCONF = 'yume.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yume.wsgi.application'

# ========== БАЗА ДАННЫХ (SQLite для разработки) ==========
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ========== КЕШ (отключён для простоты) ==========
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}

# ========== ПАРОЛИ И АУТЕНТИФИКАЦИЯ ==========
AUTH_USER_MODEL = 'users.CustomUser'
AUTH_PASSWORD_VALIDATORS = []  # упрощаем для разработки
LOGIN_URL = '/users/login/'
LOGIN_REDIRECT_URL = 'anime:home'
LOGOUT_REDIRECT_URL = 'anime:home'
SESSION_COOKIE_AGE = 30 * 24 * 60 * 60
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

# ========== ИНТЕРНАЦИОНАЛИЗАЦИЯ ==========
LANGUAGE_CODE = 'ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_L10N = True
USE_TZ = True
LOCALE_PATHS = [BASE_DIR / 'locale']

# Для Windows (если запуск на Windows)
if sys.platform.startswith('win'):
    import locale
    locale.setlocale(locale.LC_ALL, 'Russian_Russia.1251')

# ========== СТАТИЧЕСКИЕ ФАЙЛЫ ==========
STATIC_URL = '/static/'
if DEBUG:
    STATICFILES_DIRS = [BASE_DIR / 'static']
    STATIC_ROOT = None
else:
    STATICFILES_DIRS = []
    STATIC_ROOT = BASE_DIR / 'static'

# ========== МЕДИА ==========
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ========== ПОЛЯ ПО УМОЛЧАНИЮ ==========
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ========== MIME-ТИПЫ ДЛЯ JS ==========
import mimetypes
mimetypes.add_type('application/javascript', '.js')
mimetypes.add_type('text/javascript', '.js')

# ========== CORS (упрощено для разработки) ==========
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://*.github.dev",
    "https://*.githubpreview.dev",
]
CORS_ALLOW_ALL_ORIGINS = True  # для разработки (в продакшене убрать)

# ========== CSRF ==========
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://*.github.dev",
    "https://*.githubpreview.dev",
]
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'

# ========== БЕЗОПАСНОСТЬ (упрощено для разработки) ==========
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
SECURE_PROXY_SSL_HEADER = None
USE_X_FORWARDED_HOST = False
SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
SECURE_REFERRER_POLICY = "no-referrer-when-downgrade"
SECURE_CROSS_ORIGIN_OPENER_POLICY = None
X_FRAME_OPTIONS = 'DENY'
SECURE_BROWSER_XSS_FILTER = False
SECURE_CONTENT_TYPE_NOSNIFF = True

# ========== ЗАГОЛОВКИ БЕЗОПАСНОСТИ ==========
def SEOHeadersMiddleware(get_response):
    def middleware(request):
        response = get_response(request)
        response['Permissions-Policy'] = 'accelerometer=(), gyroscope=(), encrypted-media=()'
        response['Referrer-Policy'] = 'strict-origin-when-cross-origin'
        return response
    return middleware

# ========== CELERY (ОТКЛЮЧЁН) ==========
# Для демонстрации просто задаём фиктивные значения, чтобы не было ошибок импорта
CELERY_BROKER_URL = 'memory://'
CELERY_RESULT_BACKEND = 'cache+memory://'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Moscow'
CELERY_TASK_ALWAYS_EAGER = True  # выполнять задачи синхронно
CELERY_BEAT_SCHEDULE = {}

# ========== RECAPTCHA (заглушки) ==========
RECAPTCHA_PUBLIC_KEY = os.getenv('RECAPTCHA_PUBLIC_KEY', 'dummy')
RECAPTCHA_PRIVATE_KEY = os.getenv('RECAPTCHA_PRIVATE_KEY', 'dummy')
RECAPTCHA_REQUIRED_SCORE = 0.85

# ========== EMAIL (фиктивный вывод в консоль) ==========
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'test@gmail.com'
EMAIL_HOST_PASSWORD = 'dummy'
DEFAULT_FROM_EMAIL = 'test@gmail.com'

# ========== ДРУГИЕ НАСТРОЙКИ ==========
SITE_ID = 1
APPEND_SLASH = False
DEFAULT_CHARSET = 'utf-8'
FILE_CHARSET = 'utf-8'
ROBOTS_INDEX = True
SITE_DOMAIN = "localhost:8000"
SITE_LOGO = "https://yamu.su/static/img/logo.png"

# ========== НАСТРОЙКИ ДЛЯ АНИМЕ (отключаем внешние сервисы) ==========
USE_WEBP = True
WEBP_QUALITY = 85
IMAGE_CACHE_TIMEOUT = 86400 * 30
IMAGE_OPTIMIZATION = {
    'jpeg_quality': 85,
    'png_quality': 85,
    'webp_quality': 80,
    'max_width': 1920,
}
RATING_UPDATE_BATCH_SIZE = 15
RATING_UPDATE_INTERVAL = 600

# Убираем Google Indexing API (заглушка)
GOOGLE_INDEXING_API_JSON_KEY_PATH = ''
GOOGLE_INDEXING_API_SERVICE_ACCOUNT_EMAIL = ''
GOOGLE_INDEXING_PRIVATE_KEY = ''  # удаляем настоящий ключ

# Убираем Яндекс OAuth
YANDEX_OAUTH_TOKEN = ''  # удаляем настоящий токен

# Логирование (вывод в консоль)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# Дополнительные настройки безопасности (CSP) — упрощаем
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "https://kodik-add.com")
CSP_IMG_SRC = ("'self'", "data:")
CSP_FRAME_SRC = ("'self'", "https://kodik-add.com")
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'")
CSP_CONNECT_SRC = ("'self'",)

# Настройки сессий и кук
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'

# ---------- Регистрация JSON-функций для SQLite (для локальной разработки) ----------
from django.db.backends.signals import connection_created
from django.dispatch import receiver

@receiver(connection_created)
def setup_sqlite_json_functions(sender, connection, **kwargs):
    if connection.vendor == 'sqlite':
        import json
        import sqlite3

        def jsonb_array_length(json_str):
            """Возвращает длину JSON-массива или 0, если данные не массив."""
            if not json_str:
                return 0
            try:
                data = json.loads(json_str)
                if isinstance(data, list):
                    return len(data)
                return 0
            except (json.JSONDecodeError, TypeError):
                return 0

        connection.connection.create_function("jsonb_array_length", 1, jsonb_array_length)
        print("✅ Зарегистрирована функция jsonb_array_length для SQLite")