# Generated by Django 5.2.3 on 2026-06-16 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description_manual",
                    models.BooleanField(
                        default=False,
                        help_text="Если отмечено, автоматическое обновление не будет перезаписывать описание",
                        verbose_name="Описание изменено вручную",
                    ),
                ),
                (
                    "rating_last_updated",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Последнее обновление рейтинга",
                    ),
                ),
                (
                    "poster_webp",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="posters/webp/",
                        verbose_name="WebP постер",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        help_text="Автоматически генерируется из названия",
                        max_length=255,
                        verbose_name="ЧПУ-метка",
                    ),
                ),
                (
                    "shikimori_rating",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Рейтинг Shikimori"
                    ),
                ),
                ("title", models.CharField(default="Без названия", max_length=255)),
                ("description", models.TextField(blank=True)),
                ("genres", models.CharField(blank=True, max_length=255)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "shikimori_id",
                    models.CharField(
                        help_text="ID из URL Shikimori (пример: https://shikimori.one/animes/505 → 505)",
                        max_length=255,
                        unique=True,
                        verbose_name="Shikimori ID",
                    ),
                ),
                (
                    "franchise_code",
                    models.CharField(
                        blank=True,
                        help_text="Название франшизы + число для порядка. Пример: SoloLeveling1",
                        max_length=255,
                        verbose_name="Код франшизы (например: SoloLeveling2)",
                    ),
                ),
                (
                    "poster_kodik",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Постер от Kodik"
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("winter", "Зима"),
                            ("spring", "Весна"),
                            ("summer", "Лето"),
                            ("autumn", "Осень"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Сезон выпуска",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("anons", "Анонсировано"),
                            ("ongoing", "Выходит"),
                            ("released", "Завершено"),
                        ],
                        default="released",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "last_full_update",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Последнее полное обновление",
                    ),
                ),
                (
                    "total_episodes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество эпизодов"
                    ),
                ),
                (
                    "last_indexed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Последняя отправка на индексацию",
                    ),
                ),
                (
                    "slug_en",
                    models.SlugField(
                        blank=True,
                        help_text="Automatically generated from English title",
                        max_length=255,
                        null=True,
                        verbose_name="English Slug",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Franchise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Опционально, для удобства отображения",
                        max_length=255,
                        verbose_name="Название франшизы",
                    ),
                ),
                (
                    "anime_ids",
                    models.JSONField(
                        default=list,
                        help_text="Список ID в правильном порядке, например: [123, 321, 456]",
                        verbose_name="Список shikimori_id аниме",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Франшиза",
                "verbose_name_plural": "Франшизы",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Screenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="BlockedDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(default="auto_detected", max_length=100)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["domain"], name="anime_block_domain_208750_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="anime.anime",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
