# Generated by Django 5.2.3 on 2025-06-23 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_last_updated', models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление рейтинга')),
                ('shikimori_rating', models.FloatField(blank=True, null=True, verbose_name='Рейтинг Shikimori')),
                ('title', models.CharField(default='Без названия', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('genres', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('shikimori_id', models.CharField(help_text='ID из URL Shikimori (пример: https://shikimori.one/animes/505 → 505)', max_length=255, unique=True, verbose_name='Shikimori ID')),
                ('franchise_code', models.CharField(blank=True, help_text='Название франшизы + число для порядка. Пример: SoloLeveling1', max_length=255, verbose_name='Код франшизы (например: SoloLeveling2)')),
                ('poster_kodik', models.URLField(blank=True, max_length=500, verbose_name='Постер от Kodik')),
                ('season', models.CharField(blank=True, choices=[('winter', 'Зима'), ('spring', 'Весна'), ('summer', 'Лето'), ('autumn', 'Осень')], max_length=10, null=True, verbose_name='Сезон выпуска')),
                ('total_episodes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество эпизодов')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='anime.anime')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='disliked_comments', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='anime.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='anime.anime')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
