# Generated by Django 5.2.3 on 2025-06-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_anime_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Автоматически генерируется из названия', max_length=255, verbose_name='ЧПУ-метка'),
        ),
    ]
