# Generated by Django 5.2.3 on 2025-08-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_alter_anime_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='last_full_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее полное обновление'),
        ),
        migrations.AddField(
            model_name='anime',
            name='last_indexed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя отправка на индексацию'),
        ),
        migrations.AddField(
            model_name='anime',
            name='slug_en',
            field=models.SlugField(blank=True, help_text='Automatically generated from English title', max_length=255, null=True, verbose_name='English Slug'),
        ),
        migrations.AddField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('anons', 'Анонсировано'), ('ongoing', 'Выходит'), ('released', 'Завершено')], default='released', max_length=10, verbose_name='Статус'),
        ),
    ]
