# Generated by Django 5.2.3 on 2025-07-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='last_full_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее полное обновление'),
        ),
        migrations.AddField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('anons', 'Анонсировано'), ('ongoing', 'Выходит'), ('released', 'Завершено')], default='released', max_length=10, verbose_name='Статус'),
        ),
    ]
