# Generated by Django 5.2.3 on 2025-07-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_similarityvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='similarity_score',
            field=models.IntegerField(default=0, verbose_name='Рейтинг похожести'),
        ),
    ]
