# Generated by Django 5.2.3 on 2025-07-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_anime_similarity_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='similarity_score',
        ),
        migrations.DeleteModel(
            name='SimilarityVote',
        ),
    ]
