# Generated by Django 5.2.3 on 2025-08-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_remove_anime_similarity_score_delete_similarityvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='last_indexed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя отправка на индексацию'),
        ),
    ]
