# Generated by Django 5.2.3 on 2025-08-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_anime_last_indexed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='slug_en',
            field=models.SlugField(blank=True, help_text='Automatically generated from English title', max_length=255, null=True, verbose_name='English Slug'),
        ),
    ]
