# Generated by Django 5.1.6 on 2026-01-02 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_genre_anime_last_full_update_anime_last_indexed_at_and_more'),
        ('anime', '0010_anime_slug_en'),
    ]

    operations = [
    ]
