# Generated by Django 5.1.6 on 2026-01-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_merge_20260103_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='description_manual',
            field=models.BooleanField(default=False, help_text='Если отмечено, автоматическое обновление не будет перезаписывать описание', verbose_name='Описание изменено вручную'),
        ),
        migrations.AddField(
            model_name='anime',
            name='poster_webp',
            field=models.ImageField(blank=True, null=True, upload_to='posters/webp/', verbose_name='WebP постер'),
        ),
        migrations.CreateModel(
            name='BlockedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='auto_detected', max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain'], name='anime_block_domain_208750_idx')],
            },
        ),
    ]
